// The courtyard's textures, generated by tools/make-textures.mjs.
import {defineAsset} from '@engine';

export default defineAsset({
  id: 'cobbles',
  type: 'texture',
  url: '/textures/cobbles.png',
  width: 256,
  height: 256,
  licence: 'CC0-1.0',
  author: 'Lantern Courtyard',
  source: 'tools/visual-courtyard/game/tools/make-textures.mjs',
});
