import '../../src/app/styles.ts';
import './style.css';
import {createApp} from '../../src/core/app.ts';
import {appFeatures} from '../../src/core/settings/app-features.ts';
import {layerModules} from '../../src/app/layer-modules.ts';
import {compileGame} from '../../src/author/compile.ts';
import {defineBuild,defineGame,defineScene,defineSystem,defineAsset,defineSaveSection,Name,Transform,Model,ModelPoseLink} from '../../src/author/index.ts';
import {createTestApi} from '../../src/dev/test-api.ts';
import {createAppearanceDocument} from '../../src/kits/character/appearance.ts';
import {createAuthoringSession} from '../../src/kits/authoring/session.ts';
import {saveModule} from '../../src/core/save/module.ts';
import {browserPort} from '../../src/core/save/storage-port.ts';
const choices=['amber','cyan','reversed','missing','badbind','slow','failed'];
const initial={version:1,parts:{surface:'amber'},parameters:{}};
const intake=value=>createAppearanceDocument({id:'weighted-appearance',version:1,json:JSON.stringify(value),limits:{maxBytes:1024,maxNodes:16,maxDepth:4,maxParts:1,maxParameters:0},validate:v=>Object.keys(v.parts).length===1&&choices.includes(v.parts.surface)&&Object.keys(v.parameters).length===0});
const section=defineSaveSection({id:'appearance.profile',scope:'device',initial,parse(value){const d=intake(value);try{return d.read().value;}finally{d.dispose();}}});
const brief=defineBuild({goal:'Preview independently weighted modules on a coherent creator-authored pose.',genre:'diagnostic',pitch:'Optional weighted appearance comparison.',coreLoop:['Preview','Compare','Accept','Save'],devices:{targets:['desktop'],minimum:'desktop',input:['keyboard','pointer']},success:[{id:'S1',check:'Weighted vertices follow current pose; failed edits retain accepted identity and saved reload.',how:'playtest',by:'scripts/play/weighted-appearance-check.mjs'}]});
const game=defineGame({id:'weighted-appearance',version:'0.1.0',title:'Weighted appearance',firstScene:'sample'});
const assets=['source',...choices].map(id=>defineAsset({id,type:'model',url:`/__weighted-appearance/${id}.glb`,licence:'CC0-1.0',author:'Foundation Engine contributors',source:'tools/weighted-appearance/fixtures.mjs'}));
const storageKey='weighted-appearance|device|appearance.profile',local=browserPort('local');
let resetting=false;
const port={...local,set(key,value){if(key===storageKey&&resetting)throw Error('Appearance reset in progress');if(key===storageKey&&sessionStorage.getItem('weighted-deny')==='yes')throw Error('Injected diagnostic storage refusal');local.set(key,value);}};
let ctx,accepted,candidate,owner,session,save,life,models,retired=true,message='',blocked=false,history=[],pendingKind='edit',last='',angle=0,prior;
const el=id=>document.getElementById(id);
const resource=e=>ctx.modelState(e);
const groupState=g=>g?{...g,sourceState:resource(g.source),partState:resource(g.part),link:ctx.modelPoseLinkState(g.part)}:null;
const ready=g=>g&&resource(g.source).status==='ready'&&resource(g.part).status==='ready'&&ctx.modelPoseLinkState(g.part).status==='ready';
const persistence=()=>{if(!save||retired)return null;const status=save.status();if(status!=='saved')return 'unsaved:'+status;if(JSON.stringify(save.get())!==owner.read().json)return 'unsaved';try{return local.get(storageKey)?'saved':'not-saved';}catch{return 'unsaved:unavailable';}};
const read=()=>({retired,blocked,message,angle,value:owner?.read().value,accepted:ctx?groupState(accepted):null,candidate:ctx?groupState(candidate):null,history:session?.stats(),save:persistence(),resources:models?.stats()});
const show=()=>{const s=read();el('summary').textContent=blocked?'Restore needs recovery':s.save??'Loading';el('message').textContent=s.candidate?(ready(candidate)?'Candidate compatible and ready. Compare, Commit or Cancel.':s.candidate.partState.status==='failed'?'Candidate load failed. Accepted group retained; Cancel or choose another part.':['incompatible','invalid','conflict','over-budget','blocked'].includes(s.candidate.link.status)?`Candidate ${s.candidate.link.status}: ${s.candidate.link.reason}. Accepted group retained.`:message):s.accepted&&s.accepted.link.status==='incompatible'?`Accepted selection incompatible: ${s.accepted.link.reason}. Saved identity retained; choose a compatible replacement.`:message;el('persistence').textContent=`Persistence: ${s.save}`;el('state').textContent=JSON.stringify(s,null,2);el('commit').disabled=blocked||!ready(candidate);el('save').disabled=blocked||!ready(accepted);el('undo').disabled=blocked||!history.length;};
const drop=g=>{if(g){ctx.world.despawn(g.part);ctx.world.despawn(g.source);}};
const spawn=(asset,x)=>{const part=ctx.world.spawn(Name({name:'module'}),Transform({x:99}),Model({asset,playing:false}));let source;try{source=ctx.world.spawn(Name({name:'pose-source'}),Transform({x}),Model({asset:'source',playing:false,pose:[{node:'B',rotation:[0,0,Math.sin(angle/2),Math.cos(angle/2)]}]}));ctx.world.add(part,ModelPoseLink({source,nodes:['rig','A','B'].map(name=>({source:name,target:name})),inheritVisibility:true}));return {source,part,asset,x};}catch(error){ctx.world.despawn(part);if(source!==undefined)ctx.world.despawn(source);throw error;}};
const cancel=()=>{drop(candidate);candidate=null;session.cancel();pendingKind='edit';ctx.world.touch();};
const prepare=(value,kind='edit')=>{cancel();if(blocked)throw Error('Restore is blocked. Explicitly reset local saved data to recover.');const result=session.preview(owner.read().ticket,()=>JSON.stringify(value));if(result.status!=='prepared')throw Error(`Preview ${result.status}`);try{candidate=spawn(value.parts.surface,.8);pendingKind=kind;}catch(error){session.cancel();throw error;}message='Candidate loading; accepted group retained.';};
const commands={
 preview(){prepare({version:1,parts:{surface:el('part').value},parameters:{}});},
 cancel(){cancel();message='Candidate retired; accepted group retained.';},
 commit(){if(blocked||!ready(candidate))throw Error('Candidate must be compatible and ready.');const previous=owner.read().value;const result=pendingKind==='undo'?session.undo():session.commit();if(result.status!=='accepted')throw Error(`Commit ${result.status}`);if(pendingKind==='undo')history.pop();else {history.push(previous);if(history.length>8)history.shift();}drop(accepted);accepted=candidate;candidate=null;accepted.x=-2;ctx.world.get(accepted.source,Transform).x=-2;ctx.world.touch();message='Accepted coherent weighted group; save separately.';},
 undo(){if(history.length)prepare(history.at(-1),'undo');message='Previous selection prepared; accept after compatibility resolves.';},
 bend(){angle=angle===0?Math.PI/2:0;for(const g of [accepted,candidate])if(g){const m=ctx.world.get(g.source,Model);m.clip='';m.playing=false;m.pose=[{node:'B',rotation:[0,0,Math.sin(angle/2),Math.cos(angle/2)]}];}ctx.world.touch();message='Source B rotated; A stays fixed.';},
 animate(){for(const g of [accepted,candidate])if(g){const m=ctx.world.get(g.source,Model);m.pose=[];m.clip='bend';m.playing=true;}ctx.world.touch();message='Native source animation drives linked module.';},
 pause(){for(const g of [accepted,candidate])if(g)ctx.world.get(g.source,Model).playing=false;ctx.world.touch();},
 save(){if(blocked||!ready(accepted))throw Error('Accepted selection needs recovery before saving.');save.update(draft=>Object.assign(draft,structuredClone(owner.read().value)),{now:true});message='Save attempted; persistence status reports actual result.';},
 'fail-save'(){sessionStorage.setItem('weighted-deny','yes');message='Diagnostic writes refused until restored.';},
 'restore-save'(){sessionStorage.removeItem('weighted-deny');message='Writes restored; choose Save to retry.';},
 reload(){location.reload();},
 reset(){resetting=true;local.remove(storageKey);sessionStorage.removeItem('weighted-deny');sessionStorage.removeItem('weighted-corrupt');location.reload();},
};
const sync=defineSystem({id:'weighted-ui',phase:'frame',run(){if(retired)return;const value=JSON.stringify(read());if(value!==last){last=value;show();}}});
const scene=defineScene({id:'sample',title:'Weighted modules',modelPoseLinks:{},systems:[sync],view:{camera:{position:[.4,1.2,9],target:[.4,.6,0],fov:50},background:0x142132},enter(context){ctx=context;retired=false;blocked=sessionStorage.getItem('weighted-corrupt')==='yes';history=[];life=new AbortController();let raw;try{raw=local.get(storageKey);if(raw){const envelope=JSON.parse(raw);intake(envelope.value??envelope.data??envelope).dispose();}}catch{blocked=true;sessionStorage.setItem('weighted-corrupt','yes');}save=ctx.save(section);if(['newer','quarantined','unavailable'].includes(save.status())){blocked=true;sessionStorage.setItem('weighted-corrupt','yes');}owner=intake(save.get());session=createAuthoringSession(owner,{maxEntries:8,maxHistoryBytes:16384});accepted=blocked?null:spawn(owner.read().value.parts.surface,-2);candidate=null;el('part').innerHTML=choices.map(id=>`<option>${id}</option>`).join('');el('part').value=owner.read().value.parts.surface;el('controls').innerHTML=Object.keys(commands).map(id=>`<button id="${id}">${id}</button>`).join('');for(const [id,fn]of Object.entries(commands))el(id).addEventListener('click',()=>{try{fn();}catch(error){message=error.message;}show();},{signal:life.signal});el('part').addEventListener('change',()=>{cancel();message='Selection changed; preview again.';show();},{signal:life.signal});el('open').onclick=()=>{el('panel').hidden=false;el('part').focus();};el('close').onclick=()=>{el('panel').hidden=true;el('open').focus();};el('panel').addEventListener('keydown',e=>{if(e.key==='Escape'){el('panel').hidden=true;el('open').focus();}},{signal:life.signal});message=blocked?`Saved appearance needs recovery (${save.status()}); explicit Reset is available.`:'Accepted appearance loading.';show();},exit(){retired=true;life.abort();drop(candidate);drop(accepted);candidate=accepted=null;session.dispose();owner.dispose();}});
const compiled=compileGame({brief,game,defs:[scene,sync,section,...assets]});const modules=layerModules(game,brief).map(m=>m.id==='core.save'?saveModule({namespace:game.id,build:'weighted@0.1.0',storage:()=>({local:port,session:browserPort('session')})}):m);
const app=createApp([...modules,...compiled.modules],{mode:'test',flag:id=>appFeatures().enabled(id),probes:true});const booted=app.boot();window.engine=createTestApi(app,booted);
window.weightedAppearance={read,inspect(which='accepted'){const g=which==='accepted'?accepted:candidate;return g?engine.model({entity:g.part,expectedEpoch:engine.state().scene.epoch,skinVertices:[0,1,2].map(vertex=>({mesh:'surface',vertex}))}):null;},source(){return accepted?engine.model({entity:accepted.source,expectedEpoch:engine.state().scene.epoch}):null;},keep(){prior={ctx,part:candidate?.part??accepted?.part};},previous(){return prior?.ctx.modelPoseLinkState(prior.part);},dispose(){app.dispose();}};await booted;models=app.services.models;
