// The lesson as data (a helper file). Outline: two board steps, a sim, a quiz; objectives o1 and o2.
import { defineLesson } from '@kits/learn';

export default defineLesson({
  id: 'day-night', version: 1, title: 'lesson.title', ages: [8, 11],
  objectives: [{ id: 'o1', text: 'lesson.o1' }, { id: 'o2', text: 'lesson.o2' }],
  cast: [
    { id: 'teacher', name: 'lesson.cast.teacher', role: 'teacher', color: '#ffd166' },
    { id: 'sam', name: 'lesson.cast.sam', role: 'classmate', color: '#7bd88f' },
  ],
  outline: [
    { id: 'board-1', type: 'board', objective: 'o1' },
    { id: 'board-2', type: 'board', objective: 'o2' },
    { id: 'turn', type: 'sim', objective: 'o2' },
    { id: 'check', type: 'quiz', objective: 'o1' },
  ],
  scenes: {
    'board-1': {
      type: 'board', title: 'lesson.s1.title',
      board: { items: [
        { id: 'sun', kind: 'circle', at: [34, 42], r: 14, color: '#ffd166', fill: 'rgb(255 209 102 / 25%)' },
        { id: 'sun-label', kind: 'label', at: [34, 66], text: 'lesson.board.sun' },
        { id: 'earth', kind: 'circle', at: [118, 42], r: 9, color: '#6ec3ff', fill: 'rgb(110 195 255 / 25%)' },
        { id: 'earth-label', kind: 'label', at: [118, 60], text: 'lesson.board.earth' },
        { id: 'spin', kind: 'path', points: [[106, 28], [112, 24], [120, 23], [128, 26], [132, 31]], color: '#f4f1ea' },
        { id: 'spin-head', kind: 'arrow', from: [131, 29], to: [133, 33] },
        { id: 'spin-label', kind: 'label', at: [118, 18], text: 'lesson.board.spin' },
      ] },
      timeline: [
        { do: 'objectives' },
        { do: 'say', who: 'teacher', text: 'lesson.s1.hello' },
        { do: 'wait-for', event: 'next' },
        { do: 'say', who: 'teacher', text: 'lesson.s1.sun' },
        { do: 'draw', target: 'sun' },
        { do: 'write', target: 'sun-label' },
        { do: 'wait-for', event: 'next' },
        { do: 'say', who: 'teacher', text: 'lesson.s1.earth' },
        { do: 'draw', target: 'earth' },
        { do: 'write', target: 'earth-label' },
        { do: 'wait-for', event: 'next' },
        { do: 'say', who: 'sam', text: 'lesson.s1.sam-asks' },
        { do: 'say', who: 'teacher', text: 'lesson.s1.answer' },
        { do: 'wait-for', event: 'next' },
        { do: 'say', who: 'teacher', text: 'lesson.s1.spin' },
        { do: 'draw', target: 'spin' },
        { do: 'draw', target: 'spin-head' },
        { do: 'wait-for', event: 'next' },
      ],
      interrupts: {
        question: [{ do: 'say', who: 'teacher', text: 'lesson.s1.q-answer' }],
        again: [{ do: 'say', who: 'teacher', text: 'lesson.s1.again' }, { do: 'spotlight', target: 'sun' }, { do: 'spotlight', target: 'earth' }, { do: 'spotlight', target: null }],
      },
    },
    'board-2': {
      type: 'board', title: 'lesson.s2.title',
      board: { items: [
        { id: 'sun', kind: 'circle', at: [22, 45], r: 12, color: '#ffd166', fill: 'rgb(255 209 102 / 25%)' },
        { id: 'ray-1', kind: 'arrow', from: [38, 35], to: [96, 35], color: '#ffd166' },
        { id: 'ray-2', kind: 'arrow', from: [38, 45], to: [94, 45], color: '#ffd166' },
        { id: 'ray-3', kind: 'arrow', from: [38, 55], to: [96, 55], color: '#ffd166' },
        { id: 'earth', kind: 'circle', at: [112, 45], r: 14, color: '#6ec3ff' },
        { id: 'day-side', kind: 'path', points: [[112, 31], [104, 34], [99, 40], [98, 45], [99, 50], [104, 56], [112, 59]], color: '#ffd166' },
        { id: 'day', kind: 'label', at: [90, 74], text: 'lesson.board.day' },
        { id: 'night', kind: 'label', at: [136, 74], text: 'lesson.board.night' },
      ] },
      timeline: [
        { do: 'say', who: 'teacher', text: 'lesson.s2.light' },
        { do: 'draw', target: 'sun' },
        { do: 'draw', target: 'earth' },
        { do: 'wait-for', event: 'next' },
        { do: 'draw', target: 'ray-1' },
        { do: 'draw', target: 'ray-2' },
        { do: 'draw', target: 'ray-3' },
        { do: 'wait-for', event: 'next' },
        { do: 'say', who: 'teacher', text: 'lesson.s2.day' },
        { do: 'draw', target: 'day-side' },
        { do: 'write', target: 'day' },
        { do: 'wait-for', event: 'next' },
        { do: 'say', who: 'teacher', text: 'lesson.s2.night' },
        { do: 'write', target: 'night' },
        { do: 'say', who: 'sam', text: 'lesson.s2.sam' },
        { do: 'wait-for', event: 'next' },
        { do: 'say', who: 'teacher', text: 'lesson.s2.yes' },
        { do: 'wait-for', event: 'next' },
      ],
    },
    turn: {
      type: 'sim', title: 'lesson.s3.title',
      sim: { param: { id: 'spin', label: 'lesson.s3.param', min: 0, max: 360, step: 1, start: 0 }, checks: [{ objective: 'o2', atLeast: 180 }] },
      timeline: [
        { do: 'say', who: 'teacher', text: 'lesson.s3.try' },
        { do: 'camera', yaw: 0.9, pitch: 0.45, distance: 9 },
        { do: 'wait-for', event: 'param', min: 180 },
        { do: 'say', who: 'teacher', text: 'lesson.s3.night' },
        { do: 'say', who: 'teacher', text: 'lesson.s3.tap' },
        { do: 'wait-for', event: 'next' },
      ],
      interrupts: { hint: [{ do: 'say', who: 'teacher', text: 'lesson.s3.hint' }] },
    },
    check: {
      type: 'quiz', title: 'lesson.s4.title',
      timeline: [{ do: 'say', who: 'teacher', text: 'lesson.s4.intro' }, { do: 'wait-for', event: 'answer' }],
      quiz: { questions: [
        { id: 'q1', objective: 'o1', prompt: 'lesson.q1', options: [{ id: 'a', text: 'lesson.q1.a' }, { id: 'b', text: 'lesson.q1.b' }, { id: 'c', text: 'lesson.q1.c' }], answer: 'a', hints: ['lesson.q1.hint'], feedback: { right: 'lesson.right', retry: 'lesson.retry' } },
        { id: 'q2', objective: 'o2', prompt: 'lesson.q2', options: [{ id: 'a', text: 'lesson.q2.a' }, { id: 'b', text: 'lesson.q2.b' }], answer: 'b', hints: ['lesson.q2.hint'], feedback: { right: 'lesson.right', retry: 'lesson.retry' } },
        { id: 'q3', objective: 'o1', prompt: 'lesson.q3', options: [{ id: 'a', text: 'lesson.q3.a' }, { id: 'b', text: 'lesson.q3.b' }, { id: 'c', text: 'lesson.q3.c' }], answer: 'b', hints: ['lesson.q3.hint'], feedback: { right: 'lesson.right', retry: 'lesson.retry' } },
      ] },
    },
  },
});
