// scripts/lib/provenance.ts: where each shipped file came from (docs/guides/asset-provenance.md).
//
// A game keeps one provenance record for every model, texture and sound under its public/ folder, either
//   - beside the file: `<public>/models/lantern.glb` -> `<public>/models/lantern.provenance.json` (the same receipt
//     the Blender export sample writes; its `artifact`, when present, must name the file), or
//   - in `<game>/assets.provenance.json` under `assets`, keyed by the path inside public/ ("sounds/jump.ogg").
// The same file also lists the tooling that never reaches players (`tooling`) and whether anything is generated
// while the game runs (`liveGenerated`). `npm run check` (scripts/lint/provenance.ts) reports missing and broken
// records; `npm run disclosure` (scripts/disclosure.ts) turns them into store disclosure text.
//
// Owner: the creator writes the records; these functions only read. Bounds: one directory walk and one SHA-256
// per shipped file of a known kind; records are small JSON. Nothing is fetched. A record is an integrity and
// disclosure receipt, not proof of rights.
import {createHash} from 'node:crypto';
import {existsSync, readFileSync} from 'node:fs';
import {basename, dirname, extname, join} from 'node:path';
import {publicFiles} from './game-public.mjs';

export type AssetKind = 'model' | 'texture' | 'sound';
const KINDS: Record<string, AssetKind> = {
  '.glb': 'model',
  '.gltf': 'model',
  '.png': 'texture',
  '.jpg': 'texture',
  '.jpeg': 'texture',
  '.webp': 'texture',
  '.avif': 'texture',
  '.ktx2': 'texture',
  '.hdr': 'texture',
  '.exr': 'texture',
  '.ogg': 'sound',
  '.oga': 'sound',
  '.opus': 'sound',
  '.mp3': 'sound',
  '.wav': 'sound',
  '.m4a': 'sound',
  '.aac': 'sound',
  '.flac': 'sound',
  '.weba': 'sound',
};
/** The kind of a shipped file that needs a record, or null (decoders, data, records themselves). */
export const assetKind = (path: string): AssetKind | null => KINDS[extname(path).toLowerCase()] ?? null;

/** How a file was made. */
export const ORIGINS = {
  hand: 'made by a person (by hand, or with a script a person wrote)',
  'agent-blender': 'built by an AI agent driving Blender (for example through the Blender MCP server)',
  'ai-generator': 'generated by an AI model or service (3D, image, texture, sound or voice generator)',
  library: 'taken from a library or another author (Poly Haven, Kenney, a store asset)',
} as const;
export type Origin = keyof typeof ORIGINS;
const AI_ORIGINS: readonly Origin[] = ['agent-blender', 'ai-generator'];
export const isAiOrigin = (o: Origin) => AI_ORIGINS.includes(o);

/** One record. Other keys (a model receipt's bounds, generator, sourceSha256 …) are kept and not checked here. */
export interface ProvenanceRecord {
  origin: Origin;
  /** Who made it, or the original author as the licence asks to be credited. */
  author: string;
  /** The asset's own licence (SPDX where one exists). */
  licence: string;
  /** Where it came from: the script that made it, the library URL, the generator's job or page. */
  source: string;
  /** SHA-256 of the shipped file, hex. */
  sha256: string;
  /** The tool and its version: `Blender 5.2.1 LTS + Blender Lab MCP 1.0.3`, `Tripo v3.1 (web, Pro plan)`. */
  tool?: string;
  /** The AI model and version that made it: the agent's model, or the generator's model. */
  model?: string;
  /** Licence of the generator's weights (`NVIDIA Open Model License`, `proprietary service`). */
  weightsLicence?: string;
  /** The terms the generator's output is under (`Tripo Pro terms: commercial use allowed`). */
  outputLicence?: string;
  /** The prompt given, or `reference` for the image/model/sketch it was made from. One is required for AI origins. */
  prompt?: string;
  reference?: string;
  /** What a person changed afterwards, or `none`. Required for AI origins. */
  humanEdits?: string;
  /** The file name, for a record beside the file. */
  artifact?: string;
}

/**
 * AI help that is not a shipped file: `code` (code assistants, agents writing the game's code) and `other` (tests,
 * planning, reviews) are development tooling players never see; `text` means player-facing words (strings,
 * dialogue, lesson text) were written or drafted with AI, so it is disclosed as content.
 */
export interface ToolingRecord {
  use: 'code' | 'text' | 'other';
  tool: string;
  model?: string;
  note?: string;
}

export interface GameProvenance {
  /** False: nothing is generated by AI while the game runs. A string describes what is. Absent: not recorded. */
  liveGenerated?: false | string;
  tooling?: ToolingRecord[];
}

export interface AssetEntry {
  /** Path inside public/, '/' separated. */
  path: string;
  kind: AssetKind;
  /** Where the record was found ('' when none). */
  recordFile: string;
  record: ProvenanceRecord | null;
  problems: string[];
}

export interface ProvenanceReport {
  game: string;
  publicDir: string;
  assets: AssetEntry[];
  /** Problems of assets.provenance.json itself. */
  problems: string[];
  /** Null when assets.provenance.json is absent. */
  declared: GameProvenance | null;
}

const isRecord = (v: unknown): v is Record<string, unknown> => v !== null && typeof v === 'object' && !Array.isArray(v);
const text = (v: unknown): v is string => typeof v === 'string' && v.trim().length > 0;
const TOOLING_USES: readonly string[] = ['code', 'text', 'other'];

/** Problems with one record's fields, for an asset of `kind`; [] when it is complete. */
export function recordProblems(value: unknown): string[] {
  if (!isRecord(value)) return ['the record is not a JSON object'];
  const out: string[] = [];
  const origin = value.origin;
  if (!text(origin) || !(origin in ORIGINS))
    out.push(`origin: expected one of ${Object.keys(ORIGINS).join(', ')} (got ${JSON.stringify(origin ?? null)})`);
  for (const key of ['author', 'licence', 'source'] as const)
    if (!text(value[key])) out.push(`${key}: required, a nonempty string`);
  if (!text(value.sha256) || !/^[0-9a-f]{64}$/.test(value.sha256))
    out.push('sha256: required, the file’s SHA-256 in lowercase hex');
  for (const key of ['tool', 'model', 'weightsLicence', 'outputLicence', 'prompt', 'reference', 'humanEdits'])
    if (value[key] !== undefined && !text(value[key])) out.push(`${key}: expected a nonempty string when present`);
  if (origin === 'agent-blender' || origin === 'ai-generator') {
    for (const key of ['tool', 'model', 'humanEdits'] as const)
      if (!text(value[key])) out.push(`${key}: required for origin ${origin}`);
    if (!text(value.prompt) && !text(value.reference)) out.push(`prompt or reference: one is required for ${origin}`);
  }
  if (origin === 'ai-generator')
    for (const key of ['weightsLicence', 'outputLicence'] as const)
      if (!text(value[key])) out.push(`${key}: required for origin ai-generator (check the generator's terms)`);
  return out;
}

const sha256 = (file: string) => createHash('sha256').update(readFileSync(file)).digest('hex');

function readJson(file: string): {value?: unknown; problem?: string} {
  try {
    return {value: JSON.parse(readFileSync(file, 'utf8'))};
  } catch (error) {
    return {problem: `${basename(file)} is not valid JSON: ${(error as Error).message}`};
  }
}

/** Problems of assets.provenance.json's own shape, and what it declares. */
export function gameProvenanceProblems(value: unknown): {
  problems: string[];
  declared: GameProvenance;
  assets: Record<string, unknown>;
} {
  const problems: string[] = [];
  const declared: GameProvenance = {};
  if (!isRecord(value)) return {problems: ['assets.provenance.json: expected a JSON object'], declared, assets: {}};
  if (value.schema !== 1) problems.push('assets.provenance.json: schema must be 1');
  for (const key of Object.keys(value))
    if (!['schema', 'assets', 'tooling', 'liveGenerated'].includes(key))
      problems.push(`assets.provenance.json: unknown key ${key}`);
  if (value.liveGenerated !== undefined) {
    if (value.liveGenerated === false || text(value.liveGenerated)) declared.liveGenerated = value.liveGenerated;
    else problems.push('assets.provenance.json: liveGenerated must be false or a description');
  }
  if (value.tooling !== undefined) {
    if (!Array.isArray(value.tooling)) problems.push('assets.provenance.json: tooling must be a list');
    else {
      declared.tooling = [];
      for (const [i, t] of value.tooling.entries()) {
        if (!isRecord(t) || !text(t.use) || !TOOLING_USES.includes(t.use) || !text(t.tool)) {
          problems.push(`assets.provenance.json: tooling[${i}] needs use (${TOOLING_USES.join(', ')}) and tool`);
          continue;
        }
        declared.tooling.push({
          use: t.use as ToolingRecord['use'],
          tool: t.tool,
          ...(text(t.model) ? {model: t.model} : {}),
          ...(text(t.note) ? {note: t.note} : {}),
        });
      }
    }
  }
  if (value.assets !== undefined && !isRecord(value.assets))
    problems.push('assets.provenance.json: assets must be an object keyed by the path inside public/');
  return {problems, declared, assets: isRecord(value.assets) ? value.assets : {}};
}

/** Every shipped asset of `game` with its record and problems. `publicDir` defaults to `<game>/public`. */
export function readProvenance(game: string, publicDir = join(game, 'public')): ProvenanceReport {
  const problems: string[] = [];
  let declared: GameProvenance | null = null;
  let central: Record<string, unknown> = {};
  const centralFile = join(game, 'assets.provenance.json');
  if (existsSync(centralFile)) {
    const {value, problem} = readJson(centralFile);
    if (problem) problems.push(problem);
    else {
      const parsed = gameProvenanceProblems(value);
      problems.push(...parsed.problems);
      declared = parsed.declared;
      central = parsed.assets;
    }
  }
  const files = existsSync(publicDir) ? publicFiles(publicDir) : [];
  const shipped = new Set(files);
  for (const key of Object.keys(central))
    if (!shipped.has(key)) problems.push(`assets.provenance.json: ${key} is not a file under public/`);
  const assets: AssetEntry[] = [];
  for (const path of files) {
    const kind = assetKind(path);
    if (!kind) continue;
    const entry: AssetEntry = {path, kind, recordFile: '', record: null, problems: []};
    const name = basename(path);
    const sidecar = join(publicDir, dirname(path), `${name.slice(0, -extname(name).length)}.provenance.json`);
    let value: unknown;
    if (existsSync(sidecar)) {
      const read = readJson(sidecar);
      if (read.problem) entry.problems.push(read.problem);
      else if (!(isRecord(read.value) && read.value.artifact !== undefined && read.value.artifact !== name)) {
        value = read.value;
        entry.recordFile = `public/${dirname(path) === '.' ? '' : dirname(path) + '/'}${basename(sidecar)}`;
      }
    }
    if (Object.hasOwn(central, path)) {
      if (entry.recordFile) entry.problems.push(`two records: ${entry.recordFile} and assets.provenance.json`);
      else {
        value = central[path];
        entry.recordFile = 'assets.provenance.json';
      }
    }
    if (!entry.recordFile) {
      if (!entry.problems.length)
        entry.problems.push(
          `no provenance record: add public/${path.replace(/\.[^.]+$/, '')}.provenance.json or an assets.provenance.json entry`,
        );
    } else {
      const fieldProblems = recordProblems(value);
      entry.problems.push(...fieldProblems);
      if (isRecord(value) && text(value.sha256) && /^[0-9a-f]{64}$/.test(value.sha256)) {
        const actual = sha256(join(publicDir, path));
        if (actual !== value.sha256) entry.problems.push(`sha256 does not match the file (file is ${actual})`);
      }
      if (!fieldProblems.length) entry.record = value as ProvenanceRecord;
    }
    assets.push(entry);
  }
  return {game, publicDir, assets, problems, declared};
}
