/**
 * core/i18n: typed string lookup (ADR 0021; STANDARD chapter 12).
 *
 * - `t(key, vars)` requires exactly the variables the key's `en` text uses. The key → variables map is generated by
 *   `scripts/strings.mjs` into `keys.gen.ts` (`StringParams`); this module is generic over it so it never depends on
 *   the generated file.
 * - Reading levels are key variants (STD-STR-3): `key` is the standard text, `key@detailed` the detailed text (for
 *   example a guardian's or expert's reading). The level comes from the i18n default (set by the layer) or from
 *   `t(key, vars, {level})`.
 * - A key missing in the current locale falls back per key to the base locale (STD-STR-4). A key missing everywhere
 *   calls `onMissing` (DEV throws, production logs once: the caller decides) and renders the caller's `fallback`, or
 *   the key itself. Never a generic line.
 *
 * core/i18n/app-i18n.ts is the running game's instance; the narrator reads its lines through it.
 */
import { parseMessage, renderMessage, type Part, type Vars } from './format';
import { fillNarrationPattern, narrationKey, type NarrationFamilyDef, type NarrationKey, type NarrationVars } from './narration-families';

export type ReadingLevel = 'standard' | 'detailed';
export type Catalog = Readonly<Record<string, string>>;
export const DETAILED_SUFFIX = '@detailed';

/** Per-call options. `fallback` is the owner's text for an unknown key (STD-STR-4). */
export interface TOptions { level?: ReadingLevel; fallback?: string }

/** A key whose parameters are `never` takes no variables; any other key must be given exactly its variables. */
export type TArgs<P, K extends keyof P> = [P[K]] extends [never]
  ? [vars?: undefined, opts?: TOptions]
  : [vars: P[K], opts?: TOptions];

export interface I18n<P> {
  t<K extends keyof P & string>(key: K, ...args: TArgs<P, K>): string;
  /** True when the key (standard text) resolves in the current locale or the base locale. */
  has(key: string): boolean;
  locale(): string;
  setLocale(locale: string): void;
  level(): ReadingLevel;
  setLevel(level: ReadingLevel): void;
  /** Add or replace one locale's catalogue (a lazily loaded feature shard, for example). */
  addCatalog(locale: string, catalog: Catalog): void;
  /**
   * A composed narration key (STD-STR-5): the family's pattern filled with `vars`, each checked against
   * its hole's domain. A value outside the domain calls `onBadNarrationKey` (DEV throws) and otherwise returns the
   * key exactly as the pattern builds it, for the narrator to resolve (it falls back to the scene's own key).
   */
  narrationKey<H extends string>(family: NarrationFamilyDef<H>, vars: NarrationVars<H>): NarrationKey;
}

export interface I18nOptions {
  locale: string;
  catalogs: Readonly<Record<string, Catalog>>;
  baseLocale?: string;
  level?: ReadingLevel;
  onMissing?: (key: string, locale: string) => void;
  /** A composed narration key outside its family's domain. Throw to fail loudly; return to log and go on. */
  onBadNarrationKey?: (error: Error, key: string) => void;
}

export function createI18n<P>(opts: I18nOptions): I18n<P> {
  const base = opts.baseLocale ?? 'en';
  let locale = opts.locale, level: ReadingLevel = opts.level ?? 'standard';
  const catalogs = new Map<string, Record<string, string>>(Object.entries(opts.catalogs).map(([l, c]) => [l, { ...c }]));
  const parsed = new Map<string, Part[]>();
  const chain = () => (locale === base ? [base] : [locale, base]);

  function lookup(key: string, want: ReadingLevel): { text: string; locale: string } | null {
    for (const l of chain()) {
      const c = catalogs.get(l);
      if (!c) continue;
      if (want === 'detailed' && Object.hasOwn(c, key + DETAILED_SUFFIX)) return { text: c[key + DETAILED_SUFFIX], locale: l };
      if (Object.hasOwn(c, key)) return { text: c[key], locale: l };
    }
    return null;
  }
  function parts(l: string, key: string, text: string): Part[] {
    const id = l + '\u0000' + key + '\u0000' + text;
    let p = parsed.get(id);
    if (!p) { p = parseMessage(text); parsed.set(id, p); }
    return p;
  }

  return {
    t(key, ...[vars, o]) {
      const found = lookup(key, o?.level ?? level);
      if (!found) { opts.onMissing?.(key, locale); return o?.fallback ?? key; }
      // Literal labels already are their rendered value. Keeping a parsed text node and
      // a locale/key/text cache entry for each lazy catalog label retains needless strings.
      // Check both braces so malformed messages still reach the parser and throw.
      if (!found.text.includes('{') && !found.text.includes('}')) return found.text;
      return renderMessage(parts(found.locale, key, found.text), vars as Vars | undefined, found.locale);
    },
    has: key => lookup(key, 'standard') !== null,
    locale: () => locale,
    setLocale(l) { locale = l; },
    level: () => level,
    setLevel(l) { level = l; },
    addCatalog(l, catalog) { catalogs.set(l, { ...catalogs.get(l), ...catalog }); },
    narrationKey(family, vars) {
      try { return narrationKey(family, vars); } catch (e) {
        const key = fillNarrationPattern(family, vars);
        opts.onBadNarrationKey?.(e instanceof Error ? e : new Error(String(e)), key);
        return key as NarrationKey;
      }
    },
  };
}
