import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {mkdtempSync, readFileSync, rmSync, writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';

const directory = fileURLToPath(new URL('.', import.meta.url));
const target = fileURLToPath(new URL('../../src/kits/procgen/cellular-wasm-bytes.ts', import.meta.url));
const rustc = process.env.CELLULAR_RUSTC ?? 'rustc';
const version = execFileSync(rustc, ['--version'], {cwd: directory, encoding: 'utf8'}).trim();
if (version !== 'rustc 1.99.0 (b940084d7 2026-09-28)') throw new Error(`Unpinned compiler: ${version}`);
if (process.argv.slice(2).some(arg => arg !== '--check')) throw new Error('Usage: node build.mjs [--check]');
const flags = [
  '--crate-name',
  'cellular_kernel',
  '--crate-type',
  'cdylib',
  '--edition=2024',
  '--target',
  'wasm32-unknown-unknown',
  '-C',
  'opt-level=3',
  '-C',
  'panic=abort',
  '-C',
  'lto=fat',
  '-C',
  'codegen-units=1',
  '-C',
  'strip=symbols',
  '-C',
  'link-arg=--import-memory',
  '-C',
  'link-arg=--export=__heap_base',
  '-C',
  'link-arg=--stack-first',
  '-C',
  'link-arg=-zstack-size=65536',
  '-C',
  'link-arg=--initial-memory=131072',
];
const temporary = mkdtempSync(join(tmpdir(), 'foundation-cellular-wasm-'));
try {
  const artifact = join(temporary, 'kernel.wasm');
  execFileSync(rustc, ['kernel.rs', ...flags, '-o', artifact], {cwd: directory, stdio: 'inherit'});
  const bytes = readFileSync(artifact);
  const hash = data => createHash('sha256').update(data).digest('hex');
  const lines = [];
  for (let offset = 0; offset < bytes.length; offset += 24)
    lines.push(`  ${[...bytes.subarray(offset, offset + 24)].join(',')},`);
  const generated = [
    '// Generated by tools/cellular-wasm/build.mjs; do not edit. GPL-3.0-only.',
    `// Source SHA-256: ${hash(readFileSync(join(directory, 'kernel.rs')))}`,
    `// Artifact SHA-256: ${hash(bytes)}`,
    `// Compiler: ${version}`,
    `// Flags: ${flags.join(' ')}`,
    `export const SOURCE_SHA256 = '${hash(readFileSync(join(directory, 'kernel.rs')))}';`,
    '// prettier-ignore',
    'export const CELLULAR_WASM_BYTES = new Uint8Array([',
    ...lines,
    ']);',
    '',
  ].join('\n');
  if (process.argv.includes('--check')) {
    if (readFileSync(target, 'utf8') !== generated) throw new Error('WASM artifact is stale; run build.mjs');
    console.log(`cellular WASM reproducible: ${bytes.length} bytes, SHA-256 ${hash(bytes)}`);
  } else {
    writeFileSync(target, generated);
    console.log(`Generated ${target} (${bytes.length} bytes)`);
  }
} finally {
  rmSync(temporary, {recursive: true, force: true});
}
