// scripts/disclosure.ts (`npm run disclosure`): draft the Steam and itch.io AI-disclosure text from the game's
// provenance records (docs/guides/asset-provenance.md). It separates content players see or hear (shipped files
// made with AI, player-facing text written with AI) from development tooling (code assistants), which Steam's form
// does not cover. It is a draft for the creator to review and paste; it publishes nothing and fetches nothing.
// A file without a valid record makes the draft INCOMPLETE: the categories it could affect say "unknown", never "No".
//
//   npm run disclosure [-- --game <dir>] [--json] [--strict]     --strict exits 1 when the draft is incomplete
import {relative, resolve, sep, join} from 'node:path';
import {gameDir, ROOT} from './lib/game-dir.mjs';
import {gamePublicDir} from './lib/game-public.mjs';
import {
  isAiOrigin,
  ORIGINS,
  readProvenance,
  type AssetEntry,
  type AssetKind,
  type ProvenanceReport,
} from './lib/provenance';

type Answer = 'Yes' | 'No' | 'Unknown';
export interface Disclosure {
  game: string;
  complete: boolean;
  /** Files without a valid record, and record-file problems. */
  gaps: string[];
  steam: {preGenerated: string; liveGenerated: string; tooling: string};
  itch: {category: 'Graphics' | 'Sound' | 'Text & Dialog' | 'Code'; answer: Answer; basis: string}[];
  aiAssets: {path: string; kind: AssetKind; origin: string; tool: string; model: string; humanEdits: string}[];
}

const KIND_WORD: Record<AssetKind, [string, string]> = {
  model: ['3D model', '3D models'],
  texture: ['texture or image', 'textures and images'],
  sound: ['sound', 'sounds'],
};
const count = (n: number, kind: AssetKind) => `${n} ${KIND_WORD[kind][n === 1 ? 0 : 1]}`;
const list = (items: string[]) =>
  items.length < 2 ? (items[0] ?? '') : `${items.slice(0, -1).join(', ')} and ${items[items.length - 1]}`;

/** The disclosure draft for a provenance report. Pure: no file access. */
export function disclose(report: ProvenanceReport, game = report.game): Disclosure {
  const unrecorded = report.assets.filter(a => !a.record || a.problems.length);
  const gaps = [...report.problems, ...unrecorded.map(a => `public/${a.path}: ${a.problems.join('; ')}`)];
  const ai = report.assets.filter((a): a is AssetEntry & {record: NonNullable<AssetEntry['record']>} =>
    Boolean(a.record && isAiOrigin(a.record.origin)),
  );
  const tooling = report.declared?.tooling ?? [];
  const text = tooling.filter(t => t.use === 'text');
  const code = tooling.filter(t => t.use === 'code');
  const behind = tooling.filter(t => t.use !== 'text');
  const named = (t: {tool: string; model?: string}) => (t.model ? `${t.tool} (${t.model})` : t.tool);

  const kinds: AssetKind[] = ['model', 'texture', 'sound'];
  const parts: string[] = [];
  for (const kind of kinds) {
    const agent = ai.filter(a => a.kind === kind && a.record.origin === 'agent-blender');
    const generated = ai.filter(a => a.kind === kind && a.record.origin === 'ai-generator');
    if (agent.length)
      parts.push(
        `${count(agent.length, kind)} built by an AI agent writing Blender scripts (${list([...new Set(agent.map(a => named({tool: a.record.tool ?? '', model: a.record.model ?? ''})))])})`,
      );
    if (generated.length)
      parts.push(
        `${count(generated.length, kind)} generated with ${list([...new Set(generated.map(a => named({tool: a.record.tool ?? '', model: a.record.model ?? ''})))])}`,
      );
  }
  if (text.length) parts.push(`player-facing text written or drafted with ${list(text.map(named))}`);
  const edited = ai.filter(a => !/^none\.?$/i.test(a.record.humanEdits ?? '')).length;
  let preGenerated = parts.length
    ? `This game contains content made with AI tools before release: ${list(parts)}.` +
      (ai.length
        ? ` ${edited ? `${edited} of the ${ai.length} AI-made files were then edited by a person` : `None of the ${ai.length} AI-made files was edited by a person afterwards`}; the record for each file names the tool, the model and the edits.`
        : '')
    : 'No content in this game was made with AI tools.';
  if (!report.declared && !parts.length)
    preGenerated =
      'No shipped file is recorded as AI-made. Player-facing text is not recorded (add a `tooling` list to assets.provenance.json, empty if no AI was used).';
  if (unrecorded.length)
    preGenerated += ` INCOMPLETE: ${unrecorded.length} shipped file(s) have no valid provenance record, so this statement is not yet reliable.`;
  const live = report.declared?.liveGenerated;
  const liveGenerated =
    live === false
      ? 'Nothing is generated by AI while the game runs.'
      : typeof live === 'string'
        ? live
        : 'Not recorded: set liveGenerated in assets.provenance.json (false, or a description of what is generated while the game runs and the guardrails on it).';
  const toolingText = behind.length
    ? `Development tooling (not player content; Steam's form excludes efficiency tools): ${list(behind.map(t => `${named(t)} for ${t.use === 'code' ? 'code' : 'development work'}${t.note ? ` (${t.note})` : ''}`))}.`
    : report.declared
      ? 'No AI development tooling is recorded.'
      : 'Development tooling is not recorded.';

  const category = (kindsIn: AssetKind[]): {answer: Answer; basis: string} => {
    const own = report.assets.filter(a => kindsIn.includes(a.kind));
    const made = ai.filter(a => kindsIn.includes(a.kind));
    const missing = unrecorded.filter(a => kindsIn.includes(a.kind));
    if (made.length) return {answer: 'Yes', basis: `${made.length} of ${own.length} file(s) recorded as AI-made`};
    if (missing.length) return {answer: 'Unknown', basis: `${missing.length} file(s) without a valid record`};
    return {
      answer: 'No',
      basis: own.length ? `all ${own.length} file(s) recorded, none AI-made` : 'no such files ship',
    };
  };
  const declaredUse = (uses: typeof text): {answer: Answer; basis: string} =>
    uses.length
      ? {answer: 'Yes', basis: `recorded: ${list(uses.map(named))}`}
      : report.declared?.tooling
        ? {answer: 'No', basis: 'tooling list recorded without this use'}
        : {answer: 'Unknown', basis: 'no tooling list in assets.provenance.json'};

  return {
    game,
    complete: gaps.length === 0 && report.declared?.tooling !== undefined && live !== undefined,
    gaps,
    steam: {preGenerated, liveGenerated, tooling: toolingText},
    itch: [
      {category: 'Graphics', ...category(['model', 'texture'])},
      {category: 'Sound', ...category(['sound'])},
      {category: 'Text & Dialog', ...declaredUse(text)},
      {category: 'Code', ...declaredUse(code)},
    ],
    aiAssets: ai.map(a => ({
      path: a.path,
      kind: a.kind,
      origin: a.record.origin,
      tool: a.record.tool ?? '',
      model: a.record.model ?? '',
      humanEdits: a.record.humanEdits ?? '',
    })),
  };
}

/** The draft as Markdown. */
export function disclosureMarkdown(d: Disclosure) {
  const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
  return [
    `# AI disclosure draft: ${d.game}`,
    '',
    d.complete
      ? 'Status: complete. Every shipped model, texture and sound has a valid record, and tooling and live generation are recorded. Review before you paste.'
      : 'Status: **INCOMPLETE**. Do not publish this as it is; fix the gaps at the end first.',
    '',
    '## Steam (AI generated content disclosure)',
    '',
    '**Pre-generated content** (made with AI tools during development; players see or hear it):',
    '',
    d.steam.preGenerated,
    '',
    '**Live-generated content** (made with AI while the game runs):',
    '',
    d.steam.liveGenerated,
    '',
    `Not part of Steam's form: ${d.steam.tooling}`,
    '',
    '## itch.io (AI generation disclosure)',
    '',
    '| Category | Answer | Basis |',
    '|---|---|---|',
    ...d.itch.map(c => `| ${c.category} | ${c.answer} | ${cell(c.basis)} |`),
    '',
    ...(d.aiAssets.length
      ? [
          '## AI-made files',
          '',
          '| File | Origin | Tool | Model | Human edits |',
          '|---|---|---|---|---|',
          ...d.aiAssets.map(
            a =>
              `| public/${cell(a.path)} | ${a.origin}: ${cell(ORIGINS[a.origin as keyof typeof ORIGINS] ?? '')} | ${cell(a.tool)} | ${cell(a.model)} | ${cell(a.humanEdits)} |`,
          ),
          '',
        ]
      : []),
    ...(d.gaps.length ? ['## Gaps', '', ...d.gaps.map(g => `- ${g}`), ''] : []),
    'Generated by `npm run disclosure` from the provenance records (docs/guides/asset-provenance.md). Records are receipts, not proof of rights; check each generator’s terms yourself.',
    '',
  ].join('\n');
}

if (process.argv[1] && resolve(process.argv[1]).endsWith(`scripts${sep}disclosure.ts`)) {
  const dir = gameDir();
  const report = readProvenance(dir, gamePublicDir({game: join(dir, 'public')}));
  const draft = disclose(report, relative(ROOT, dir).split(sep).join('/'));
  console.log(process.argv.includes('--json') ? JSON.stringify(draft, null, 2) : disclosureMarkdown(draft));
  process.exitCode = process.argv.includes('--strict') && !draft.complete ? 1 : 0;
}
